version: '3.2'

services:
  elasticsearch:
    build:
      context: elastic/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elastic/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk

  server:
    build:
      context: server/
    volumes:
      - type: bind
        source: ./server/app
        target: /app
        read_only: true
    command: "/start-reload.sh"
    ports:
      - 80:80


networks:
  elk:
    driver: bridge


volumes:
  elasticsearch:
